- mikupad.html
Quick fix for koboldcpp EoS ban. Just swapped ignore_eos for the koboldcpp equivalent if koboldcpp is selected.
> Allow banning of EoS on koboldcpp

- mikupad.html
official llama.cpp server [supports api keys](https://github.com/ggerganov/llama.cpp/tree/master/examples/server#:~:text=Set%20an%20api%20key%20for%20request%20authorization)
> allow api key usage for llama.cpp

- mikupad.html
A regenerate button discards the previous generation (undo) and starts a new one. If no undo operation is possible, regenerate is not shown or enabled.
It's pretty useful when the user is not happy with the last generation and wishes to redo it.
The button is small with a round arrow:
Also added a Ctrl + R shortcut for it, and added shortcuts for undo and redo as well (Ctrl + Z, Ctrl + Y) which are pretty standard.
> Add regenerate button

- mikupad.html
The redo button was not attaching the memory to the prompt when sending through ooba's text-generation-webui api. I asked chatGPT to fix it and this seemed to work, but I'm not sure if it's the ideal solution.
> Redo button fix

- mikupad.html
Added the option to clone the current session (equivalent to exporting it and importing it again with a JSON file).
I believe this can be very useful for preserving a particular session and experimenting with a copy.
By default, the new session will add "Cloned" at the beginning of the name.
> Add button to clone the current session

- mikupad.html
Added the option (by default enabled to preserve the current behavior) to preserve the position of the cursor after a prediction, or move it to the end of the new text.
The use for this would be to allow the user to start writing right away after the generation is done.
It may have been interesting to add a space after the last word generated by the AI, but I'm not sure it would always have the desired effect, so it merely overrides the default behavior of preserving the cursor with no further modifications. If there's a selection, it will be preserved, however.
> After generation set cursor end

- mikupad.html
Added a button in the settings modal dialog to allow to export the current text of the prompt area:
The name of the file is the name of the current session in .txt format. Nothing else is exported, only the text that has been co-written with the AI:
I've used a blob after checking out with chatGPT because the text could be potentially very long. To be honest, I don't know if we'd run into other issues first as the text grew larger. I know that for example NovelAI doesn't load all the text necessarily.
> Export to plaintext

- mikupad.html
Sessions are similar to stories in NovelAI. For example, I keep in one of the sessions lorebook information about a novel I'm writing. However, sometimes it's hard to tell which session I am on, and it can lead to overwriting information.
I think that adding the session name after the title can be very helpful:
Personally I'd put the session name first and mikupad after that (this is what NovelAI does) but for now I append it after it.
> Show session name in window title

- .gitignore
- mikupad.html
- server/package.json
- server/server.js
- server/start.bat
Closes #34
Connecting to a session server allows you to share your sessions between multiple devices over the LAN, the implementation currently is very basic and there are no safeguards or automatic synchronization between the local database and the server database.
**Edit**: I have decided to remove the ability to manually connect to the session server. Now, it will automatically connect to the session server if you open MikuPad through the server URL
> Add support for a basic session server

- mikupad.html
ignore the other closed one, accidentally pushed with wrong variable.
This pr only removes ```logprobs``` and adds ```api.together.xyz``` conditionals
```openaiModels() -> getModels()``` is still broken. 
Here's some models to put in ```Model```. [Model String for API](https://docs.together.ai/docs/inference-models) or [api.together.xyz/v1/models](https://api.together.xyz/v1/models)
> fix togetherai (openai-compatible)

- mikupad.html
Fixes #55. When I tried to use mikupad with Together, inference failed because the API won't accept more than 1 n_probs in the request. Moreover, fetching the model list also failed. These two commits fix these problems.
> Fix a couple of things that break when using Together AI

- mikupad.html
OpenRouter's API OpenAI-compatible URL has a trailing /api, which the `normalizeEndpoint` normally removes, making all requests to OpenRouter fail. This commit makes it so this does not happen.
> Add OpenRouter compatibility

- .github/workflows/compile_mikupad.yml
A workflow that automatically builds `mikupad_compiled.html`. Feel free to close if this isn't something you want.
It runs the compile.sh script, and then automatically pushed to the repository.
I've got it running on [my main branch](https://github.com/neCo2/mikupad) if you want to see the result.
~~It kept bugging me about updating to the v4 actions and the npm version, so I did that, but for some reason it gets stuck on `Cleaning up orphan processes` for 20+ minutes now. It builds and pushes no problem, but then the action gets stuck at the end and doesn't actually complete.~~
~~It appears that this might be caused by issues with github rather than the action itself: https://github.com/orgs/community/discussions/15133#discussioncomment-5469332
Everything working as intended now. Looks …
> added compile workflow

- mikupad.html
Removed all the useless stuff from #62, now it just gives you a little token count display next to the title of the text field/at the bottom right of the modals. There's also a table in the context modal showing all token counts.
> Feature/Persistent Context Token Counts

- mikupad.html
This allows prediction from any arbitrary position in the text, currently it will predict until the next character is reached.
https://github.com/lmg-anon/mikupad/assets/139719567/ecb713bc-26b3-402b-8d2c-6d76db9b9cc6
https://github.com/lmg-anon/mikupad/assets/139719567/0da602bf-b237-4f73-82e8-fb7eb976dfec
> Implement basic fill-in-the-middle support

- mikupad.html
When chat mode is active, the following error occurs at the end of generation, and the instruct prefix fails to be added to the end of the prompt.
```
Uncaught TypeError: chunk.completion_probabilities[0] is undefined
llamaCppCompletion file:///C:/Programs/mikupad/mikupad.html:1357
```
Changing the operator to optional chaining should take care of the problem.
> Fix Uncaught TypeError: chunk.completion_probabilities[0] is undefined in Chat Mode

- mikupad.html
I think the undefined `fimTemplate`s were causing problems with the `replaceNewlines` function when trying to generate after switching the template. Again a `?` should fix the issue.
```
Uncaught TypeError: value is undefined
replaceNewlines mikupad.html:3581
```
> Fix Uncaught TypeError: value is undefined when switching Chat Templates

- mikupad.html
Adding a search and replace function. Currently accessible via a button below the editor preferences button.
The UI for search and replace uses a draggable component. The "active" surface for that is the darkened area with the title.
Right now, it can do plaintext and regex replacements. I want to add template replacements too, but maybe I should wait for your chat completions PR for that one.
> Feature/Search and Replace

- mikupad.html
This PR replaces the API type numbers (0, 2, 3) with constants `API_xxx` to make the code more readable.
> Use constants for API types

- mikupad.html
Fixes #87
I found Mikupad shows up very badly on e-ink tablet screens due to all of the themes having non-white backgrounds.
So I added a new theme called "eReader" which:
- Sets the background to pure white and the text to pure black.
- Used `font-family: monospace` as this seems to slow up with the crispest edges.
- Used `font-size: 16px` as this too seems to be slightly crisper than the default `15px` (likely getting interpolated).
- Changed to use `--color-miku: #08f` for slightly better contrast.
- Made the `prompt-overlay` use slightly less transparency for much better contrast.
Overall it looks much clearer now and even on greyscale screens the colourised-overlay is mostly interpretable.
> Added "eReader" theme with improved contrast for e-ink screens

- mikupad.html
Fixes #84
This just removes any that are zero, but could also remove any that round down to `0.00%` like this:
```javascript
${probs ? html`
<div
id="probs"
style=${{
'display': 'none'
}}>
${probs.map((prob, i) => {
const probPercentage = (prob.prob * 100).toFixed(2);
if (probPercentage === '0.00') return null;
const index = currentPromptChunk?.index;
const isCurrentToken = promptChunks[index]?.prob == prob.prob;
return html`<button key=${i} className=${isCurrentToken ? 'current' : ''} onClick=${() => switchCompletion(index, prob)}>
<div className="tok">${replaceUnprintableBytes(prob.tok_str)}</div>
<div className="prob">${probPercentage}%</div>
</button>`;
}).filter(Boolean)}
</div>` : null}
```
but if the samplers are set up to select an (extremely unlikely!) sub top-10 `0.00005` …
> Removed any zero probability tokens from hover pop-up

- mikupad.html
Added buttons for exporting and importing the world info entries using the SillyTavern format to the world info modal.
For any parameters that are present in SillyTavern and not on MikuPad, it uses default values in the exported file, and ignores them when importing.
Exporting is done via a direct file download, while importing is done via a file chooser. When importing, if there are already entries in the session, the user is asked whether they want to replace them or import the new ones alongside the existing ones.
Partially addresses what is discussed in #41
> Add import and export buttons to the world info modal

- mikupad.html
When using ooba text generation web ui as a backend, I was running into 422 errors when I tried to have my sequence breakers set to the following value: ["\n", ":", "\"", "*"]
When I updated the text value for dry sequence breakers to the default value from the presets, [\"\\n\", \":\", \"\\\"\", \"*\"], I encountered an error saying that it was not a valid json.
I updated the code so where it will not automatically json.parse the drySequenceBreakers value, so my original value can be sent. In the api logs for the ooba server, it shows that the value is received as: 'dry_sequence_breakers': '["\\n", ":", "\\"", "*"]'
This change works for my use case, but it seems like it might disrupt the existing functionality. To ensure compatibility, I also updated the error checking logic to remove …
> remove automatic json parsing and update error check

- mikupad.html
- server/server.js
This drastically cuts down on memory usage which matters on mobile devices, and also calling /all with a mikupad server running with a lot of sessions previously would cause node.js to balloon in memory usage, and even if given the RAM the  ```res.json({ ok: true, result: all });``` would cause RangeError: Invalid string length.
This is a draft PR as it does not function with the IndexedDBAdapter, I would appreciate it if you could handle that, or at least verify that you are fine with this approach, and I'll then work on that, but I'm not very familiar with IndexedDB and couldn't see a way to efficiently handle the new operations.
> Allow importing multiple files at once and only keep active session in sessions object
